D/dip/config/routes.rb
Dip::Application.routes.draw do
  resources :teachers

  resources :static_pages

  resources :news

  resources :type_courses

  resources :courses

end

D/dip/app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :content, :title
end

D/dip/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end
end

D/dip/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

D/dip/app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

D/dip/app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

D/dip/app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_pages.each do |static_page| %>
  <tr>
    <td><%= static_page.title %></td>
    <td><%= static_page.content %></td>
    <td><%= link_to 'Show', static_page %></td>
    <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
    <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static page', new_static_page_path %>

D/dip/app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

D/dip/app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @static_page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @static_page.content %>
</p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>