D/dip/config/routes.rb
Dip::Application.routes.draw do
  resources :teachers

  resources :static_pages

  resources :news

  resources :type_courses

  resources :courses

end

D/dip/app/controllers/type_courses_controller.rb
class TypeCoursesController < ApplicationController
  # GET /type_courses
  # GET /type_courses.json
  def index
    @type_courses = TypeCourse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @type_courses }
    end
  end

  # GET /type_courses/1
  # GET /type_courses/1.json
  def show
    @type_course = TypeCourse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type_course }
    end
  end

  # GET /type_courses/new
  # GET /type_courses/new.json
  def new
    @type_course = TypeCourse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type_course }
    end
  end

  # GET /type_courses/1/edit
  def edit
    @type_course = TypeCourse.find(params[:id])
  end

  # POST /type_courses
  # POST /type_courses.json
  def create
    @type_course = TypeCourse.new(params[:type_course])

    respond_to do |format|
      if @type_course.save
        format.html { redirect_to @type_course, notice: 'Type course was successfully created.' }
        format.json { render json: @type_course, status: :created, location: @type_course }
      else
        format.html { render action: "new" }
        format.json { render json: @type_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /type_courses/1
  # PUT /type_courses/1.json
  def update
    @type_course = TypeCourse.find(params[:id])

    respond_to do |format|
      if @type_course.update_attributes(params[:type_course])
        format.html { redirect_to @type_course, notice: 'Type course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_courses/1
  # DELETE /type_courses/1.json
  def destroy
    @type_course = TypeCourse.find(params[:id])
    @type_course.destroy

    respond_to do |format|
      format.html { redirect_to type_courses_url }
      format.json { head :no_content }
    end
  end
end

D/dip/app/helpers/type_courses_helper.rb
module TypeCoursesHelper
end

D/dip/app/views/type_courses/_form.html.erb
<%= form_for(@type_course) do |f| %>
  <% if @type_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_course.errors.count, "error") %> prohibited this type_course from being saved:</h2>

      <ul>
      <% @type_course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

D/dip/app/views/type_courses/edit.html.erb
<h1>Editing type_course</h1>

<%= render 'form' %>

<%= link_to 'Show', @type_course %> |
<%= link_to 'Back', type_courses_path %>

D/dip/app/views/type_courses/index.html.erb
<h1>Listing type_courses</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @type_courses.each do |type_course| %>
  <tr>
    <td><%= type_course.title %></td>
    <td><%= link_to 'Show', type_course %></td>
    <td><%= link_to 'Edit', edit_type_course_path(type_course) %></td>
    <td><%= link_to 'Destroy', type_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type course', new_type_course_path %>

D/dip/app/views/type_courses/new.html.erb
<h1>New type_course</h1>

<%= render 'form' %>

<%= link_to 'Back', type_courses_path %>

D/dip/app/views/type_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @type_course.title %>
</p>


<%= link_to 'Edit', edit_type_course_path(@type_course) %> |
<%= link_to 'Back', type_courses_path %>